name: 'Simple custom container action'
description: 'Almost nothing'
inputs:
  name: 'Name'
  description: 'Name to print'
  required: true
  default: 'Felipe'
outputs:
  msg:
    description: 'Message greeting the person pass in the input'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.name }}
    - 'polite'